chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.chat_view),
    path('ajax/', views.chat_response, name='chat_ajax'),
    path('<uuid>/', views.message_view, name='message'),
]

echo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from users.views import CustomLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('follows/', views.follows_feed),
    path('ajax/', views.ajax_response),
    path('search/', views.search_response),
    path('accounts/login/', CustomLoginView.as_view()),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('posts/', include('posts.urls')),
    path('chat/', include('chat.urls')),
    path('alerts/', include('notifications.urls')),
    path('browse/', include('news.urls')),
    path('settings/', views.settings_view),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('newpost/', views.create_post, name='create_post'),
    path('<uuid>/', views.post_detail_view, name='post_detail')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('profile/<uuid>/', views.profile_view, name='profile'),
    path('user_data/', views.EchoUserResourceView.as_view(), name='user_data'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="author" content="Damon Turcotte" />
  <meta name="keywords" content="Damon Turcotte social social&nbsp;media developer application Echo Echo&nbsp;Network network social&nbsp;network web&nbsp;development Lethbridge Alberta" />
  <meta property="og:title" content="Echo Social Network" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="https://echonetwork.app" />
  <title>{{title|capfirst}}</title>
  {% load static %}
  <link rel="shortcut icon" href="{% static 'icons/icon.svg' %}" type="image/svg">
  <style>
    @font-face {
      font-family: "coda";
      src: url({% static 'fonts/Coda/Coda.ttf' %}) format(truetype);
      font-display: block;
    }
    @font-face {
      font-family: "righteous";
      src: url({% static 'fonts/Righteous/Righteous-Regular.ttf' %}) format(truetype);
    }
  </style>
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.min.js">
    $(document).ready(function () {
      console.log("jQuery initialized.");
    });
  </script>

</head>

<body style="text-rendering: geometricPrecision;">
  <header>
    <div class='header-container'>
        {% if user.is_authenticated %}
        <a class='user-header-link' href="/users/profile/{{user.uuid}}">
          <img class='user-header-avatar' src="{{user.avatar.url}}">
        </a>
        {% endif %}

      <div onclick="location.href='/'" class='logo-container'>
        
        <img src="{% static 'icons/logo.svg' %}">
        
        <div class='logo'>
          Echo
        </div>
      </div>

      

        {% if user.is_authenticated %}
        <div class='auth-container'>
          <a class="auth logout" href="{% url 'logout' %}?next={{request.path}}">
            <span>Log out</span>
          </a>
        </div>

        <a class="logout-btn" href="{% url 'logout' %}?next={{request.path}}">
          <svg fill="#dc3545" width="35px" height="35px" viewBox="-102.4 -102.4 1228.80 1228.80" stroke="#dc3545" stroke-width="51.2" transform="rotate(0)">
            <g stroke-linecap="round" stroke-linejoin="round"></g><g> <path d="M868 732h-70.3c-4.8 0-9.3 2.1-12.3 5.8-7 8.5-14.5 16.7-22.4 24.5a353.84 353.84 0 0 1-112.7 75.9A352.8 352.8 0 0 1 512.4 866c-47.9 0-94.3-9.4-137.9-27.8a353.84 353.84 0 0 1-112.7-75.9 353.28 353.28 0 0 1-76-112.5C167.3 606.2 158 559.9 158 512s9.4-94.2 27.8-137.8c17.8-42.1 43.4-80 76-112.5s70.5-58.1 112.7-75.9c43.6-18.4 90-27.8 137.9-27.8 47.9 0 94.3 9.3 137.9 27.8 42.2 17.8 80.1 43.4 112.7 75.9 7.9 7.9 15.3 16.1 22.4 24.5 3 3.7 7.6 5.8 12.3 5.8H868c6.3 0 10.2-7 6.7-12.3C798 160.5 663.8 81.6 511.3 82 271.7 82.6 79.6 277.1 82 516.4 84.4 751.9 276.2 942 512.4 942c152.1 0 285.7-78.8 362.3-197.7 3.4-5.3-.4-12.3-6.7-12.3zm88.9-226.3L815 393.7c-5.3-4.2-13-.4-13 6.3v76H488c-4.4 0-8 3.6-8 8v56c0 4.4 3.6 8 8 8h314v76c0 6.7 7.8 10.5 13 6.3l141.9-112a8 8 0 0 0 0-12.6z"></path></g>
          </svg>
        </a>
        {% else %}
        <div class='auth-container'>
          <a class="auth signup" href="{% url 'users:signup' %}">
            <span>Sign Up</span>
          </a>

          <a class='auth login' href="{% url 'login' %}">
            <span>Log In</span>
          </a>
        </div>

        <a class='login-btn' href="{% url 'login' %}">
          <svg fill="#83f100" width="35px" height="35px" viewBox="-102.4 -102.4 1228.80 1228.80" stroke="#83f100" stroke-width="51.2">
            <g stroke-linecap="round" stroke-linejoin="round"></g><g><path d="M521.7 82c-152.5-.4-286.7 78.5-363.4 197.7-3.4 5.3.4 12.3 6.7 12.3h70.3c4.8 0 9.3-2.1 12.3-5.8 7-8.5 14.5-16.7 22.4-24.5 32.6-32.5 70.5-58.1 112.7-75.9 43.6-18.4 90-27.8 137.9-27.8 47.9 0 94.3 9.3 137.9 27.8 42.2 17.8 80.1 43.4 112.7 75.9 32.6 32.5 58.1 70.4 76 112.5C865.7 417.8 875 464.1 875 512c0 47.9-9.4 94.2-27.8 137.8-17.8 42.1-43.4 80-76 112.5s-70.5 58.1-112.7 75.9A352.8 352.8 0 0 1 520.6 866c-47.9 0-94.3-9.4-137.9-27.8A353.84 353.84 0 0 1 270 762.3c-7.9-7.9-15.3-16.1-22.4-24.5-3-3.7-7.6-5.8-12.3-5.8H165c-6.3 0-10.2 7-6.7 12.3C234.9 863.2 368.5 942 520.6 942c236.2 0 428-190.1 430.4-425.6C953.4 277.1 761.3 82.6 521.7 82zM395.02 624v-76h-314c-4.4 0-8-3.6-8-8v-56c0-4.4 3.6-8 8-8h314v-76c0-6.7 7.8-10.5 13-6.3l141.9 112a8 8 0 0 1 0 12.6l-141.9 112c-5.2 4.1-13 .4-13-6.3z"></path></g>
          </svg>
        </a>
        {% endif %}

      
    </div>
  </header>

  <main>
    <div class='nav-container'>
      <div class='user-display'>
        {% if user.is_authenticated %}
        <a class='user-link' href="/users/profile/{{user.uuid}}">
          <img class='user-avatar' src="{{user.avatar.url}}">
        </a>
        {% else %}
        <div class='guest-text'>Browsing as Guest</div>
        {% endif %}
      </div>
        {% if user.is_authenticated %}
        <a class='new-post' href="{% url 'posts:create_post' %}">
          <div class='new-post-container'>
            <svg class='new-post-icon' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M481 31C445.1-4.8 386.9-4.8 351 31l-15 15L322.9 33C294.8 4.9 249.2 4.9 221.1 33L135 119c-9.4 9.4-9.4 24.6 0 33.9s24.6 9.4 33.9 0L255 66.9c9.4-9.4 24.6-9.4 33.9 0L302.1 80 186.3 195.7 316.3 325.7 481 161c35.9-35.9 35.9-94.1 0-129.9zM293.7 348.3L163.7 218.3 99.5 282.5c-48 48-80.8 109.2-94.1 175.8l-5 25c-1.6 7.9 .9 16 6.6 21.7s13.8 8.1 21.7 6.6l25-5c66.6-13.3 127.8-46.1 175.8-94.1l64.2-64.2z"/></svg>
            <span class="new-post-text">Post</span>
          </div>
        </a>
        {% endif %}
      <nav>

        <ul class='nav-list'>
          <li>
            <a class='nav-item' href="{% url 'home' %}">           
              <svg class='nav-icon' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path d="M543.8 287.6c17 0 32-14 32-32.1c1-9-3-17-11-24L512 185V64c0-17.7-14.3-32-32-32H448c-17.7 0-32 14.3-32 32v36.7L309.5 7c-6-5-14-7-21-7s-15 1-22 8L10 231.5c-7 7-10 15-10 24c0 18 14 32.1 32 32.1h32v69.7c-.1 .9-.1 1.8-.1 2.8V472c0 22.1 17.9 40 40 40h16c1.2 0 2.4-.1 3.6-.2c1.5 .1 3 .2 4.5 .2H160h24c22.1 0 40-17.9 40-40V448 384c0-17.7 14.3-32 32-32h64c17.7 0 32 14.3 32 32v64 24c0 22.1 17.9 40 40 40h24 32.5c1.4 0 2.8 0 4.2-.1c1.1 .1 2.2 .1 3.3 .1h16c22.1 0 40-17.9 40-40V455.8c.3-2.6 .5-5.3 .5-8.1l-.7-160.2h32z"/></svg>
              <span class='nav-text'>Home</span>
            </a>
          </li>
          <li>
            <a class='nav-item' href="/browse/">
              <svg class='nav-icon' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M0 128C0 92.7 28.7 64 64 64H448c35.3 0 64 28.7 64 64V384c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V128zm64 32v64c0 17.7 14.3 32 32 32H416c17.7 0 32-14.3 32-32V160c0-17.7-14.3-32-32-32H96c-17.7 0-32 14.3-32 32zM80 320c-13.3 0-24 10.7-24 24s10.7 24 24 24h56c13.3 0 24-10.7 24-24s-10.7-24-24-24H80zm136 0c-13.3 0-24 10.7-24 24s10.7 24 24 24h48c13.3 0 24-10.7 24-24s-10.7-24-24-24H216z"/></svg>
              <span class='nav-text'>Browse</span>
            </a>
          </li>
          <li>
            <a class='nav-item' href="/alerts/">
              <svg class='nav-icon' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M224 0c-17.7 0-32 14.3-32 32V51.2C119 66 64 130.6 64 208v18.8c0 47-17.3 92.4-48.5 127.6l-7.4 8.3c-8.4 9.4-10.4 22.9-5.3 34.4S19.4 416 32 416H416c12.6 0 24-7.4 29.2-18.9s3.1-25-5.3-34.4l-7.4-8.3C401.3 319.2 384 273.9 384 226.8V208c0-77.4-55-142-128-156.8V32c0-17.7-14.3-32-32-32zm45.3 493.3c12-12 18.7-28.3 18.7-45.3H224 160c0 17 6.7 33.3 18.7 45.3s28.3 18.7 45.3 18.7s33.3-6.7 45.3-18.7z"/></svg>
              <span class='nav-text'>Alerts</span>
            </a>
          </li>
          <li>
            <a class='nav-item' href="/chat/">
              <svg class='nav-icon' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M48 64C21.5 64 0 85.5 0 112c0 15.1 7.1 29.3 19.2 38.4L236.8 313.6c11.4 8.5 27 8.5 38.4 0L492.8 150.4c12.1-9.1 19.2-23.3 19.2-38.4c0-26.5-21.5-48-48-48H48zM0 176V384c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V176L294.4 339.2c-22.8 17.1-54 17.1-76.8 0L0 176z"/></svg>
              <span class='nav-text'>Messages</span>
            </a>
          </li>
          <li>
            <a class='nav-item' href="/settings/">
              <svg class='nav-icon' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M495.9 166.6c3.2 8.7 .5 18.4-6.4 24.6l-43.3 39.4c1.1 8.3 1.7 16.8 1.7 25.4s-.6 17.1-1.7 25.4l43.3 39.4c6.9 6.2 9.6 15.9 6.4 24.6c-4.4 11.9-9.7 23.3-15.8 34.3l-4.7 8.1c-6.6 11-14 21.4-22.1 31.2c-5.9 7.2-15.7 9.6-24.5 6.8l-55.7-17.7c-13.4 10.3-28.2 18.9-44 25.4l-12.5 57.1c-2 9.1-9 16.3-18.2 17.8c-13.8 2.3-28 3.5-42.5 3.5s-28.7-1.2-42.5-3.5c-9.2-1.5-16.2-8.7-18.2-17.8l-12.5-57.1c-15.8-6.5-30.6-15.1-44-25.4L83.1 425.9c-8.8 2.8-18.6 .3-24.5-6.8c-8.1-9.8-15.5-20.2-22.1-31.2l-4.7-8.1c-6.1-11-11.4-22.4-15.8-34.3c-3.2-8.7-.5-18.4 6.4-24.6l43.3-39.4C64.6 273.1 64 264.6 64 256s.6-17.1 1.7-25.4L22.4 191.2c-6.9-6.2-9.6-15.9-6.4-24.6c4.4-11.9 9.7-23.3 15.8-34.3l4.7-8.1c6.6-11 14-21.4 22.1-31.2c5.9-7.2 15.7-9.6 24.5-6.8l55.7 17.7c13.4-10.3 28.2-18.9 44-25.4l12.5-57.1c2-9.1 9-16.3 18.2-17.8C227.3 1.2 241.5 0 256 0s28.7 1.2 42.5 3.5c9.2 1.5 16.2 8.7 18.2 17.8l12.5 57.1c15.8 6.5 30.6 15.1 44 25.4l55.7-17.7c8.8-2.8 18.6-.3 24.5 6.8c8.1 9.8 15.5 20.2 22.1 31.2l4.7 8.1c6.1 11 11.4 22.4 15.8 34.3zM256 336c44.2 0 80-35.8 80-80s-35.8-80-80-80s-80 35.8-80 80s35.8 80 80 80z"/></svg>
              <span class='nav-text'>Settings</span>
            </a>
          </li>
        </ul>

      </nav>
    </div>

    <section>
      {% block content %}
      {% endblock %}
    </section>

    <aside>
      <div class="side">
        <div class="side-container">
          <span>New Users</span>
        </div>

        {% for user in new_users %}
        <div class='side-user' onclick="location.pathname='/users/profile/{{user.uuid}}/'">
          <div class="side-avatar">
            <img src="{{user.avatar.url}}">
          </div>
          <div class="side-username">{{user.username}}</div>
        </div>
        {% endfor %}

        {% for article in side_articles %}
        <div class="side-container">
          <div class="news-container">
            <a class="news-link" href="/browse/{{article.category}}/{{article.uuid}}/">
              <img class="news-img" src="{{article.image}}" alt="news article image">
              <div class="news-content">
                <div class="news-title">
                  {{article.title}}
                </div>
                <div class="news-footer">
                  <div class="news-source">{{article.source}}</div>
                </div>
              </div>
            </a>
          </div>
        </div>
        {% endfor %}
      </div>
    </aside>
  </main>

  <script src="{% static 'echo.js' %}"></script>
</body>
</html>